### ISSUE TITLE
Remove Sendgrid dependency

### ISSUE THREAD

**Issue by alextaylor000** [BrewhouseTeam/brewhouse-rails-template#34]
Leaving this here as reminder: could we remove the Sendgrid dependencies and replace them with SparkPost, once we get that up and running?

**Comment by pcreux** [comment]
We could yes. What's the benefit of using SparkPost over Sendgrid? Don't
they require the sending domain to be verified?

**Comment by alextaylor000** [comment]
I figured it would be best to move this to SparkPost since we'll be using it for Goodbits.. I was under the impression that SendGrid didn't work out too well! ;)

**Comment by pcreux** [comment]
Right. Sendgrid didn't work to well to do mass-email campaigns. It's been working great for transactional emails though. :)

When Mandrill was launched 2-3 years ago, everyone moved over to Mandrill as they were "better" (in a way) than Sendgrid. It then became a paid addon on Heroku and they are now a paid option on Mailchimp.

I would be worried to see such a thing happening to SparPost offer - that's why I'm on the fence here. Sendgrid has been doing a good enough job for years. It's likely to keep on for the years to come.

**Comment by alextaylor000** [comment]
I see, that makes sense (transactional vs campaigns). In that case, perhaps it's best to leave Sendgrid in the template for now!

**Comment by pcreux** [comment]
Sounds good. :)

Feel free to open new issues or create pull request as you bump into things. I believe that we should improve the documentation on how to deploy to Heroku as the first `git push` does not get Heroku to take `app.json` into account.
